- name: restart apache
  service:
    name: apache2
    state: restarted

- name: Create httpd config directories for CentOS
  file:
    path: "{{ httpd_conf_directory }}/{{ item }}/"
    state: directory
    mode: 0754
  with_items:
    - "conf-available"
    - "conf-enabled"
  when: ansible_os_family == "RedHat"

- name: Install Riprap httpd config file
  template:
    src: "riprap.conf.j2"
    dest: "{{ httpd_conf_directory }}/conf-available/riprap.conf"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0744

- name: Symlink Riprap httpd config file into action
  file:
    src: "{{ httpd_conf_directory }}/conf-available/riprap.conf"
    dest: "{{ httpd_conf_directory_enabled }}/riprap.conf"
    owner: "{{ webserver_app_user }}"
    group: "{{ webserver_app_user }}"
    mode: 0754
    state: link
  notify: restart apache
